import React,{useState} from 'react'
import { useAuth } from './Auth'
import { Button, Input, Field } from './UI'
import { Icon } from './Icons'

export default function LoginPage(){
  const {login}=useAuth(); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [otp,setOtp]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false)
  const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{await login(email,password,otp)}catch(err){setError(err.message); if(String(err.message).toLowerCase().includes('otp')||String(err.message).toLowerCase().includes('mfa')) setOtp(otp||'')}finally{setBusy(false)}}
  return <main className="login-page"><section className="login-brand"><div className="login-brand-inner"><img src="/jsan-logo.jpg" alt="JSAN"/><span className="eyebrow light">Business Development & Revenue Intelligence</span><h1>From pursuit to<br/><em>predictable revenue.</em></h1><p>PursuitNova gives every relationship an owner, every meeting an outcome, every action accountability, and leadership one trusted view of growth.</p><div className="login-proof"><div><Icon name="pipeline"/><strong>Pipeline discipline</strong><span>Prospect to close</span></div><div><Icon name="forecast"/><strong>Revenue confidence</strong><span>Pipeline · Best Case · Commit</span></div><div><Icon name="leadership"/><strong>Leadership clarity</strong><span>Hierarchy-aware intelligence</span></div></div></div></section><section className="login-panel"><form className="login-card" onSubmit={submit}><div className="product-mark"><span>PN</span><div><strong>PursuitNova</strong><small>JSAN internal platform</small></div></div><div><span className="eyebrow">Secure workspace</span><h2>Welcome back</h2><p>Sign in to your revenue command center.</p></div>{error&&<div className="inline-error">{error}</div>}<Field label="Work email" required><Input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="username"/></Field><Field label="Password" required><Input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/></Field>{otp!==''&&<Field label="Authenticator code"><Input value={otp} onChange={e=>setOtp(e.target.value)} inputMode="numeric" placeholder="6-digit code"/></Field>}<Button type="submit" disabled={busy}>{busy?'Signing in…':'Sign in to PursuitNova'}</Button></form></section></main>
}
