import React,{useEffect,useMemo,useState} from 'react'
import { api } from '../lib/api'
import { dateText } from '../lib/format'
import { Button,Empty,ErrorBanner,Pill,SectionHeader,Select,statusTone } from '../components/UI'
import { navigate } from '../lib/router'

export default function ActionsPage({onToast}){
 const [filter,setFilter]=useState('all'); const [rows,setRows]=useState([]); const [error,setError]=useState(null)
 const load=()=>{setError(null);return api.get('/api/actions?filter='+encodeURIComponent(filter)).then(setRows).catch(setError)}
 useEffect(()=>{load()},[filter])
 const counts=useMemo(()=>({total:rows.length,overdue:rows.filter(x=>x.overdue).length,today:rows.filter(x=>x.due_date===new Date().toISOString().slice(0,10)).length,open:rows.filter(x=>!['Completed','Cancelled'].includes(x.status)).length}),[rows])
 const update=async(a,status)=>{try{await api.put(`/api/actions/${a.id}`,{status});onToast?.({message:`Action ${status.toLowerCase()}`});load()}catch(e){onToast?.({type:'error',message:e.message})}}
 return <><SectionHeader eyebrow="Execution discipline" title="Actions" text="Turn every meeting commitment into a visible owner, due date and outcome." actions={<Select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All visible actions</option><option value="my">My actions</option><option value="overdue">Overdue</option><option value="today">Due today</option><option value="upcoming">Upcoming</option><option value="completed">Completed</option></Select>}/><div className="mini-kpis"><div><span>Open work</span><strong>{counts.open}</strong></div><div><span>Overdue</span><strong className="text-danger">{counts.overdue}</strong></div><div><span>Due today</span><strong>{counts.today}</strong></div><div><span>Visible actions</span><strong>{counts.total}</strong></div></div><ErrorBanner error={error} onRetry={load}/><section className="panel"><div className="action-board">{rows.map(a=><div className={a.overdue?'action-board-row overdue':'action-board-row'} key={a.id}><span className={`priority priority-${String(a.priority).toLowerCase()}`}>{a.priority}</span><button className="action-link" onClick={()=>navigate(`lead/${a.lead_id}`)}><strong>{a.description}</strong><span>{a.company_name} · {a.assigned_to_name}</span></button><div className="action-due"><span>Due</span><strong className={a.overdue?'text-danger':''}>{dateText(a.due_date)}</strong></div><Pill tone={a.overdue?'danger':statusTone(a.status)}>{a.overdue?'Overdue':a.status}</Pill><div className="row-actions">{a.status!=='Completed'&&<Button variant="text" onClick={()=>update(a,'Completed')}>Complete</Button>}{a.status==='Open'&&<Button variant="text" onClick={()=>update(a,'In Progress')}>Start</Button>}</div></div>)}{!rows.length&&<Empty title="No actions in this view" text="You're clear for the selected filter."/>}</div></section></>
}
