"""Build a blank JSAN technical-response template from a completed response document.

Keeps the source document's styles, page setup, header/footer, section headings and table
skeletons; removes every answer (body paragraphs, bullet text and table cell content).
"""
import re
import shutil
import sys
import zipfile
import xml.etree.ElementTree as ET

W = 'http://schemas.openxmlformats.org/wordprocessingml/2006/main'
Wb = '{%s}' % W

# 'header' = first row is a column-header row, data rows below it are blanked and trimmed.
# 'label'  = first column labels the row, so labels stay and the value columns are blanked.
TABLE_MODES = ['label', 'header', 'header', 'header', 'header', 'header',
               'label', 'header', 'header', 'header', 'header', 'header']
BLANK_ROWS = 4
GENERIC = [('WSDOT-Specific', 'Client-Specific'), ('WSDOT', 'Client')]
# Renumbered / de-tendered heading captions: no amendment numbers or sample-data identifiers
HEADING_FIXES = {
    '10. Updated Exhibit B - Technical Response Development Matrix': '10. Exhibit B - Technical Response Development Matrix',
    '11. Amendment 2 - SR522 Sample Data Validation Plan': '11. Sample Data Validation Plan',
    '12.1 Golden sample test cases': '11.1 Golden sample test cases',
}


def set_text(el, value):
    ts = list(el.iter(Wb + 't'))
    for i, t in enumerate(ts):
        t.text = value if i == 0 else ''
    if not ts:
        run = ET.SubElement(el, Wb + 'r')
        ET.SubElement(run, Wb + 't').text = value


def clean_part(name, blob):
    """Strip the client's own details from the parts we copy over untouched."""
    if name.endswith('.rels'):
        blob = re.sub(rb'<Relationship[^>]*TargetMode="External"[^>]*/>', b'', blob)
    if name == 'word/document.xml':
        blob = re.sub(rb'<w:hyperlink[^>]*/>|<w:hyperlink[^>]*>.*?</w:hyperlink>', b'', blob, flags=re.S)
    if name in ('docProps/core.xml', 'docProps/app.xml', 'word/header1.xml'):
        blob = re.sub(rb'WSDOT', b'[Client]', blob)
        blob = re.sub(rb'SR522', b'[sample data]', blob)
        blob = re.sub(rb'\d{4}-\d{4}', b'[solicitation no.]', blob)
        blob = re.sub(rb'Enterprise LiDAR/? ?/? ?Imagery Viewer', b'[solicitation title]', blob)
        for tag, value in ((b'dc:title', b'JSAN Technical Response Template'),
                           (b'cp:subject', b'Blank technical response template'),
                           (b'cp:keywords', b'JSAN, RFP, technical response, template'),
                           (b'dc:creator', b'Generated by scripts/make_technical_response_template.py'),
                           (b'cp:lastModifiedBy', b'Generated by scripts/make_technical_response_template.py')):
            blob = re.sub(b'<%s>.*?</%s>' % (tag, tag), b'<%s>%s</%s>' % (tag, value, tag), blob, flags=re.S)
    return blob


def text_of(el):
    return ''.join(t.text or '' for t in el.iter(Wb + 't'))


def genericise(el):
    for t in el.iter(Wb + 't'):
        if t.text:
            for src, dst in GENERIC:
                t.text = t.text.replace(src, dst)


def blank_paragraph(p):
    """Drop everything the author typed but keep the paragraph mark and its formatting."""
    for child in list(p):
        if child.tag != Wb + 'pPr':
            p.remove(child)


def blank_cell(tc):
    for p in tc.findall(Wb + 'p'):
        blank_paragraph(p)
    if not tc.findall(Wb + 'p'):
        tc.append(ET.Element(Wb + 'p'))


def new_empty_row(template_row):
    row = ET.fromstring(ET.tostring(template_row))
    for tc in row.findall(Wb + 'tc'):
        blank_cell(tc)
    return row


def process_table(tbl, mode):
    rows = tbl.findall(Wb + 'tr')
    if not rows:
        return
    if mode == 'label':
        genericise(rows[0])
        for row in rows:
            for tc in row.findall(Wb + 'tc')[1:]:
                blank_cell(tc)
        return
    genericise(rows[0])
    for row in rows[1:]:
        for tc in row.findall(Wb + 'tc'):
            blank_cell(tc)
    # Keep the header plus a few empty rows to fill in; drop the rest of the answered rows
    fillers = [new_empty_row(rows[-1]) for _ in range(BLANK_ROWS)]
    for row in rows[1:]:
        tbl.remove(row)
    for row in fillers:
        tbl.append(row)


def run(src, dst):
    with zipfile.ZipFile(src) as z:
        names = z.namelist()
        doc = z.read('word/document.xml')
        other = {n: z.read(n) for n in names if n != 'word/document.xml'}

    # Preserve every namespace prefix the source declares, otherwise Word rejects the output
    for prefix, uri in re.findall(r'\bxmlns(?::([\w.\-]+))?="([^"]+)"', doc[:doc.index(b'>')].decode('utf8')):
        ET.register_namespace(prefix or '', uri)

    root = ET.fromstring(doc)
    body = root.find(Wb + 'body')
    tables = [el for el in body if el.tag == Wb + 'tbl']
    if len(tables) != len(TABLE_MODES):
        print('WARNING: %d tables found, %d modes configured' % (len(tables), len(TABLE_MODES)))

    kept_headings = 0
    for el in list(body):
        if el.tag == Wb + 'p':
            style = el.find('%spPr/%spStyle' % (Wb, Wb))
            name = style.get(Wb + 'val') if style is not None else ''
            if name in ('Title', 'Heading1', 'Heading2'):
                genericise(el)
                kept_headings += 1
                caption = text_of(el).strip()
                if name == 'Title':
                    set_text(el, '[Client] - [Solicitation name]')
                elif caption in HEADING_FIXES:
                    set_text(el, HEADING_FIXES[caption])
            else:
                body.remove(el)
        elif el.tag == Wb + 'tbl':
            process_table(el, TABLE_MODES[tables.index(el)] if el in tables else 'header')

    out = ET.tostring(root, encoding='UTF-8', xml_declaration=True)
    with zipfile.ZipFile(dst, 'w', zipfile.ZIP_DEFLATED) as z:
        for name, blob in other.items():
            z.writestr(name, clean_part(name, blob))
        z.writestr('word/document.xml', clean_part('word/document.xml', out))
    print('headings kept: %d, tables: %d -> %s' % (kept_headings, len(tables), dst))


if __name__ == '__main__':
    run(sys.argv[1], sys.argv[2])
